version: '3'
services:
  web1:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./html1:/usr/share/nginx/html
  
  web2:
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./html2:/usr/share/nginx/html