#cloud-config
users:
  - name: admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

packages:
  - mysql-server
  - phpmyadmin
  - php
  - php-mysql
  - apache2

runcmd:
  - systemctl enable mysql
  - systemctl start mysql
  - systemctl enable apache2
  - systemctl start apache2
  - ln -s /etc/phpmyadmin/apache.conf /etc/apache2/conf-enabled/phpmyadmin.conf
  - systemctl restart apache2