version: '3'
services:
  web1:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./html1:/usr/share/nginx/html
    networks:
      - webnet
  
  web2:
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./html2:/usr/share/nginx/html
    networks:
      - webnet
  
  web3:
    image: nginx:alpine
    ports:
      - "8003:80"
    volumes:
      - ./html3:/usr/share/nginx/html
    networks:
      - webnet
  
  loadbalancer:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - webnet
    depends_on:
      - web1
      - web2
      - web3

networks:
  webnet: