---
- name: Configure MySQL and PHPMyAdmin
  hosts: dbserver
  become: yes
  tasks:
    - name: Install MySQL and PHPMyAdmin
      apt:
        name:
          - mysql-server
          - phpmyadmin
          - php
          - php-mysql
          - apache2
        state: present
        update_cache: yes

    - name: Set MySQL root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Configure PHPMyAdmin Apache config
      file:
        src: /etc/phpmyadmin/apache.conf
        dest: /etc/apache2/conf-enabled/phpmyadmin.conf
        state: link
      notify: restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted