---
- name: Provision KVM VMs
  hosts: localhost
  become: yes
  tasks:
    - name: Create webserver VM
      community.libvirt.virt:
        name: webserver
        command: define
        xml: |
          <domain type='kvm'>
            <name>webserver</name>
            <memory unit='MiB'>2048</memory>
            <vcpu>2</vcpu>
            <os>
              <type arch='x86_64'>hvm</type>
              <boot dev='hd'/>
            </os>
            <devices>
              <disk type='file' device='disk'>
                <source file='/var/lib/libvirt/images/webserver.qcow2'/>
                <target dev='vda' bus='virtio'/>
              </disk>
              <interface type='network'>
                <source network='default'/>
                <model type='virtio'/>
              </interface>
            </devices>
          </domain>

    - name: Create dbserver VM
      community.libvirt.virt:
        name: dbserver
        command: define
        xml: |
          <domain type='kvm'>
            <name>dbserver</name>
            <memory unit='MiB'>4096</memory>
            <vcpu>2</vcpu>
            <os>
              <type arch='x86_64'>hvm</type>
              <boot dev='hd'/>
            </os>
            <devices>
              <disk type='file' device='disk'>
                <source file='/var/lib/libvirt/images/dbserver.qcow2'/>
                <target dev='vda' bus='virtio'/>
              </disk>
              <interface type='network'>
                <source network='default'/>
                <model type='virtio'/>
              </interface>
            </devices>
          </domain>