version: '3'
services:
  web:
    build: ./web
    ports:
      - "8086:80"
    volumes:
      - ./web/html:/var/www/html
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8087:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  mysql_data:
  grafana_data: